<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>GreeACLocalServer.DeviceEmulator</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\GreeACLocalServer.Device\GreeACLocalServer.Device.csproj" />
  </ItemGroup>

</Project>
